host: example.com # CHANGE

coreContainer:
  image: docker.nexus.dataspac.es/core-container:1.2.0
  ingress:
    path: /(.*)
    rewriteTarget: /$1
    clusterIssuer: letsencrypt
    ingressClass: nginx
  environment:
    - name: ENABLE_OCSP
      value: "false"
    - name: ENABLE_CRL
      value: "false"

adminUi:
  enabled: true
  image: docker.nexus.dataspac.es/ui/core-container-ui:master
  ingress:
    path: /ui/(.*)
    rewriteTarget: /$1
    clusterIssuer: letsencrypt
    ingressClass: nginx

ids:
  info:
    idsid: urn:ids:enershare:connectors:ORGANISATION_NAME:CONNECTOR_NAME # CHANGE
    curator: urn:ids:enershare:participants:ORGANISATION_NAME # CHANGE
    maintainer: urn:ids:enershare:participants:ORGANISATION_NAME # CHANGE
    titles:
      - Enershare Meter Consumer Example@en # CHANGE
    descriptions:
      - Enershare Meter Consumer Example@en # CHANGE
    accessUrl:
      - https://{{ .Values.host }}/router

  security:
    apiKeys:
      - id: default
        key: APIKEY-sgqgCPJWgQjmMWrKLAmkETDE
        roles:
          - DATA_APP
          - PEF_MANAGER
    users:
      - id: admin
        # -- BCrypt encoded password (defaults to enershare)
        password: $2a$12$cOEhv/gcpyCFs5KkObTbweQ0axqwIuKysZdeJMArNxHCXWzYayddu
        roles:
          - ADMIN

  daps:
    url: https://daps.enershare.dataspac.es/v2

  broker:
    id: urn:ids:enershare:connectors:MetadataBroker
    address: https://broker.enershare.dataspac.es/infrastructure
    autoRegister: true

  # routes:
  #   ingress:
  #     http:
  #       - dataApp: http://{{ template "tsg-connector.fullname" . }}-openapi-data-app-http:8080/router
  #         endpoint: router
  #         parameters: "&matchOnUriPrefix=true"

containers:
  - type: data-app
    name: openapi-data-app
    image: docker.nexus.dataspac.es/data-apps/openapi-data-app:2.1.0
    apiKey: APIKEY-sgqgCPJWgQjmMWrKLAmkETDE
    config:
      openApi:
        usePolicyEnforcement: false
        agents:
          - id: urn:ids:enershare:connectors:ORGANISATION_NAME:CONNECTOR_NAME:ConsumerAgent # CHANGE
            title: Consumer Agent # CHANGE
          # # Example provider agent configuration
          # - id: urn:ids:enershare:connectors:ORGANISATION_NAME:CONNECTOR_NAME:ProviderAgent
          #   title: Provider Agent
          #   openApiBaseUrl: https://app.swaggerhub.com/apiproxy/registry/maarten.kollenstart/Enershare-Metering-Data-Measurement-API/
          #   versions:
          #     - 0.1.0
          #   backEndUrlMapping:
          #     0.1.0: http://backendservice:80
          #   # contentStandard: https://saref.etsi.org/core/v3.1.1/
          #   # keywords:
          #   # - keywords
          #   # spatialCoverage:
          #   #   latitude: 53.247521272012065
          #   #   longitude: 6.530003456591867
          #   # temporalCoverage:
          #   #   begin: "2021-05-03"
          #   #   end: "2021-06-09"
    services:
      - port: 8080
        name: http
        ingress:
          path: /data-app/(.*)
          rewriteTarget: /$1
          clusterIssuer: letsencrypt
          ingressClass: nginx