{{- if .Values.adminUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tsg-connector.fullname" . }}-core-container-ui
  labels: {{ include "tsg-connector.labels" $ | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.adminUi.nodePort }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.adminUi.nodePort }}
      nodePort: {{ . }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "tsg-connector.fullname" . }}-core-container-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}