{{- if and .Values.coreContainer.secrets.idsIdentity.enabled (not .Values.coreContainer.secrets.idsIdentity.existing) }}
{{- with .Values.coreContainer.secrets.idsIdentity }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels: {{ include "tsg-connector.labels" $ | nindent 4 }}
  {{- with $.Values.deployment.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ids.crt: {{ index .data "ids.crt" | b64enc }}
  ids.key: {{ index .data "ids.key" | b64enc }}
  ca.crt: {{ index .data "ca.crt" | b64enc }}
{{- end }}
{{- end }}