{{- if .Values.coreContainer }}
{{- with .Values.coreContainer.persistentVolume }}
  {{- if not .disableClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - {{ .accessModes | default "ReadWriteOnce" }}
  storageClassName: {{ .storageClassName | default "default" }}
  resources:
    requests:
      storage: {{ .storageSize }}
---
  {{- end }}
  {{- end }}
{{- end }}