{{- range $container := .Values.containers }}
  {{- range $container.services | default (list (dict "port" 8080 "name" "http")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tsg-connector.fullname" $ }}-{{ $container.name }}-{{ .name }}
  labels: {{ include "tsg-connector.labels" $ | nindent 4 }}
  {{- with $.Values.deployment.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if hasKey . "nodePort" }}
  type: NodePort
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      name: {{ .name }}
      protocol: TCP
      nodePort: {{ .nodePort }}
{{- else }}
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      name: {{ .name }}
      protocol: TCP
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "tsg-connector.fullname" $ }}-{{ $container.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
  {{- end }}
{{- end }}