{{- range .Values.containers }}
  {{- if eq .type "data-app" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tsg-connector.fullname" $ }}-{{ .name }}-config
  labels: {{ include "tsg-connector.labels" $ | nindent 4 }}
  {{- with $.Values.deployment.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  application.yaml: |-
    {{- include "tsg-connector.data-app-configmap" (list . $) | nindent 4 }}
---
  {{ end }}
  {{- range .configMaps }}
  {{- if not .existing }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels: {{ include "tsg-connector.labels" $ | nindent 4 }}
  {{- with $.Values.deployment.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- with .data }}
data: {{ toYaml . | nindent 2 }}
{{- end }}
{{- with .binaryData }}
binaryData: {{ toYaml . | nindent 2 }}
{{- end }}
---
  {{- end }}
  {{- end }}
---
{{- end }}