# -- Default host for ingress resources
host: tsg-connector.domain.com

coreContainer:
  # -- Replicas as specified in the core container deployment
  replicaCount: 1
  # -- Core Container docker image name
  image: docker.nexus.dataspac.es/core-container:1.1.0
  # Ingress Service configuration
  ingress:
    # -- Ingress path
    path: /(.*)
    # -- Ingress rewrite target
    rewriteTarget: /$1
  # -- Persistent volume configuration
  persistentVolume:
    # -- Persistent Volume name
    name: artifact-resources
    # -- Mount Path inside the container
    mountPath: /resources
    # -- Storage Size
    storageSize: 1Gi

adminUi:
  # -- Toggle for enabling the Core Container Administration UI
  enabled: true
  # -- Docker image to use for the UI
  image: docker.nexus.dataspac.es/core-container-ui:feature-open-sourcing
  ingress:
    # -- Ingress path
    path: /ui(/|$)(.*)
    # -- Ingress rewrite target
    rewriteTarget: /$2
    # -- Ingress clusterIssuer for automatic TLS certificate request by Cert Manager
    clusterIssuer: letsencrypt

# IDS Core Container configuration
ids:
  # Generic information on the IDS connector for usage in the Self Description that will be shared with the Broker
  info:
    # -- IDS Component Identity (URI based identifier)
    idsid: IDS_COMPONENT_ID
    # -- IDS Participant Identity, aimed at the participant that is responsible for the contents of the connector (URI based identifier)
    curator: IDS_PARTICIPANT_ID
    # -- IDS Participant Identity, aimed at the participant that is responsible for the technical side of the connector (URI based identifier)
    maintainer: IDS_PARTICIPANT_ID
    # -- Title of the Connector
    titles:
      - CONNECTOR TITLE@en
    # -- Description of the Connector
    descriptions:
      - CONNECTOR DESCRIPTION@en
    # -- Publicly accessible access URL(s) of the Connector
    accessUrl:
      - https://{{ .Values.host }}/router

  # Dynamic Attribute Provisioning Service (DAPS) configuration
  daps:
    # -- Dynamic Attribute Provisioning Service URL
    url: DAPS_URL

  # Broker Configuration
  broker:
    # -- Broker IDS Identifier
    id: BROKER_ID
    # -- Broker Access URL
    address: BROKER_ACCESS_URL

  # Core Container API Security for data apps (API Keys) and admin UI (user credentials)
  security:
    # API User Configuration
    users:
      - # -- User identifier (also used as username for the user)
        id: admin
        # -- BCrypt encoded password
        password: $2a$12$Xx4uZNtOBu91N0.D1GBi6ePelIJbNT8UzDppN.fU0P4lomlG/BcCm
        # -- User role assignments
        roles:
          - ADMIN
